### ISSUE TITLE
cannot start relayer 

### ISSUE THREAD

**Issue by chaosma** [Snowfork/polkadot-ethereum#119]
After I deployed ethereum smart contract using truffle and ran the parachain bridge, I got error when running relayer:

```build/artemis-relay run --config /tmp/relay-config.toml
Using config file: /tmp/relay-config.toml

ERRO[0000] Failed to initialize relayer                  
error="json: cannot unmarshal object into Go value of type []struct { Type string; Name string; Inputs []abi.Argument; Outputs []abi.Argument; StateMutability string; Constant bool; Payable bool; Anonymous bool }"

Error: json: cannot unmarshal object into Go value of type []struct { Type string; Name string; Inputs []abi.Argument; Outputs []abi.Argument; StateMutability string; Constant bool; Payable bool; Anonymous bool }
```

Here is my relay-config.toml:
```[ethereum]
endpoint = "ws://localhost:9545/"
[ethereum.bridge]
address = "0x722bd05E96b1841cFdfb79E174867541c2AaDEa5"

abi = "/tmp/Bridge.json"
[ethereum.apps.eth]
address = "0xd4b4131bcF86B14B28c4bf2D40A17D88e5fbC2f3"

abi = "/tmp/ETHApp.json"
[ethereum.apps.erc20]
address = "0xb8fDBE6AC4264654B3290108237F7A3C94A70221"

abi = "/tmp/ERC20App.json"
[substrate]
endpoint = "ws://127.0.0.1:9944/"
```

Is any hint for where is wrong? What is the supported golang version for relayer? Thanks!

**Comment by johnwhitton** [comment]
Debugging this the issue is when it's trying to parse the /tmp/Bridge.json
https://github.com/Snowfork/polkadot-ethereum/blob/main/relayer/chain/ethereum/contract.go#L68
The file exists and has valid.json 
Also tried replacing it with this and it still errored
```
{
  "contractName": "Bridge"
}
```
Also it the relayer readme.md
it is unclear what the value should be for
`export ARTEMIS_ETHEREUM_KEY=603a72b0c0a65d9728353714d74291ea439c6816`
My assumption is it should be the private key from the first address in Truffle Develop, e.g.
```
Private Keys:
(0) 4ea8f082a462a86cf8fa940b1934a6f72661703783585412d0da8e60efXXXXXX
```

**Comment by vgeddes** [comment]
> After I deployed ethereum smart contract using truffle and ran the parachain bridge, I got error when running relayer:
> 
> ```
> Using config file: /tmp/relay-config.toml
> 
> ERRO[0000] Failed to initialize relayer                  
> error="json: cannot unmarshal object into Go value of type []struct { Type string; Name string; Inputs []abi.Argument; Outputs []abi.Argument; StateMutability string; Constant bool; Payable bool; Anonymous bool }"
> 
> Error: json: cannot unmarshal object into Go value of type []struct { Type string; Name string; Inputs []abi.Argument; Outputs []abi.Argument; StateMutability string; Constant bool; Payable bool; Anonymous bool }
> ```
> 
> Here is my relay-config.toml:
> 
> ```
> endpoint = "ws://localhost:9545/"
> [ethereum.bridge]
> address = "0x722bd05E96b1841cFdfb79E174867541c2AaDEa5"
> 
> abi = "/tmp/Bridge.json"
> [ethereum.apps.eth]
> address = "0xd4b4131bcF86B14B28c4bf2D40A17D88e5fbC2f3"
> 
> abi = "/tmp/ETHApp.json"
> [ethereum.apps.erc20]
> address = "0xb8fDBE6AC4264654B3290108237F7A3C94A70221"
> 
> abi = "/tmp/ERC20App.json"
> [substrate]
> endpoint = "ws://127.0.0.1:9944/"
> ```
> 
> Is any hint for where is wrong? What is the supported golang version for relayer? Thanks!

@chaosma your config file should begin with this line:
```
[ethereum]
```

We're using Go 1.14 for the relayer

**Comment by johnwhitton** [comment]
Actually I'm working with @chaosma and I think he just left out the line.
The actual issue was we were doing a `cp ./build/contracts/*.json /tmp/.`
and then pointing the config to the /tmp directory
But I think the relayer is expecting the abi only, so modifying the json to remove everything but the abi worked.
We're getting this error
```
ERRO[0000] Failed to initialize relayer                  error="failed to generate keyring pair from secret: exit status 1"
Error: failed to generate keyring pair from secret: exit status 1
```
So I'm questioning if we have the configuration set correctly and we're unsure what values should be used for the environment variables ARTEMIS_SUBSTRATE_KEY and ARTEMIS_ETHEREUM_KEY
here's what we have 
```
johnlaptop relayer (main) $ echo $ARTEMIS_ETHEREUM_KEY
0x4ea8f082a462a86cf8fa940b1934a6f72661703783585412d0da8e60ef915cad
johnlaptop relayer (main) $ echo $ARTEMIS_SUBSTRATE_KEY
//Relay
```
and 
```
[ethereum]
endpoint = "ws://localhost:9545/"

[ethereum.bridge]
address = "0xd785A0142b073A8aE39f646D390bF01539E1A33e"
abi = "/tmp/Bridge.json"

[ethereum.apps.eth]
address = "0x077a96eB9Ab3998311D4e4107758B455E754CB98"
abi = "/tmp/ETHApp.json"

[ethereum.apps.erc20]
address = "0xEEA874E878aA76Fa0bdC3D12990692B8739767c4"
abi = "/tmp/ERC20App.json"

[substrate]
endpoint = "ws://127.0.0.1:9944/"
```

**Comment by johnwhitton** [comment]
I think it may be a problem with the subkey command using `inspect` instead of `inspect-key`

[This](https://github.com/Snowfork/go-substrate-rpc-client/blob/master/signature/signature.go#L52) is the line in the go-substrate-rpc-client

This is what I have installed on my machine

```
johnlaptop relayer (main) $ subkey inspect //Relay
error: The subcommand 'inspect' wasn't recognized
	Did you mean 'inspect-key'?

If you believe you received this message in error, try re-running with 'subkey -- inspect'

USAGE:
    subkey <SUBCOMMAND>

For more information try --help
johnlaptop relayer (main) $ subkey inspect-key //Relay
Secret Key URI `//Relay` is account:
  Secret seed:      0xa3885c744488891225df7830e5a492971a70d6cda031e92cbf25104f5b69f22d
  Public key (hex): 0xcc5b1c48ab38a6f87438f07f5f224b2ccdae4c7c619a41c66a2e2d25ac300336
  Account ID:       0xcc5b1c48ab38a6f87438f07f5f224b2ccdae4c7c619a41c66a2e2d25ac300336
  SS58 Address:     5Ggeh38xrCy49HYrh26QETuQmppaapygTLKQWds7upStaZYK
johnlaptop relayer (main) $ subkey --version
subkey 2.0.0-rc6
johnlaptop relayer (main) $
```

**Comment by vgeddes** [comment]
Hey @johnwhitton we've only tested the relayer with subkey v2.0.0-rc4. I do know there were some changes in the API from rc4 to rc6.

Your environment variables look fine though.

**Comment by chaosma** [comment]
It works on my side
