### ISSUE TITLE
Store secrets in AWS secrets

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#138]
Our Ansible tooling needs to access various secrets in order to generate configuration for our services. We're currently using [Ansible Vault](https://docs.ansible.com/ansible/latest/user_guide/vault.html) to store these secrets in encrypted form in our repo. 

This isn't ideal as our repo is public and everyone has access to the ciphertext. So we should try and use AWS Secrets instead.

Ansible Vault is probably still fine for secrets with minor impact such as login usernames, etc.

**Comment by musnit** [comment]
we are no longer using ansible, and those secrets are nolonger relevant, so closing this
