### ISSUE TITLE
Lock in version of Rust ethash

### ISSUE THREAD

**Issue by Rizziepit** [Snowfork/polkadot-ethereum#148]
`artemis-ethereum` and `pallet-verifier-lightclient` rely on the Rust ethash implementation at https://github.com/rust-ethereum/ethash. The latest published version is 0.4.0 which uses `ethereum-types` ^0.8 and `primitive-types` ^0.6. However, we use 0.9 and 0.7 respectively. To avoid messy type conversions, we either need to get a new version of ethash published, or maintain our own fork like Near did (https://github.com/nearprotocol/rust-ethash?branch=upgrade-eth-types). We're currently using the Near fork

**Comment by musnit** [comment]
@Rizziepit I'd suggest going with whatever is easiest for us atm. If the near fork is working fine on current mainnent blocks then let's fork it and stick with it until rust-ethereum is updated.

**Comment by vgeddes** [comment]
We're now using our fork of ethash at https://github.com/Snowfork/ethash, since the upstream repo is basically unmaintained it seems.
