### ISSUE TITLE
Restrict message size on our parachain

### ISSUE THREAD

**Issue by philipstanislaus** [Snowfork/polkadot-ethereum#149]
To reduce attack vectors, our parachain should restrict the maximum message size. Not sure what a reasonable limit might be, but I propose that few chains would need more than 2,048 bits (8 * 256 bit words).

**Comment by Rizziepit** [comment]
#390 resolves this. Heads up @vgeddes that #390 should be ported to the basic channel if/when you overhaul the basic channel
