### ISSUE TITLE
Error in XCMP specification document

### ISSUE THREAD

**Issue by carltraveler** [Snowfork/polkadot-ethereum#151]
> https://github.com/Snowfork/polkadot-ethereum/blob/main/docs/specs/xcmp.md#alice-transfers-21-polkaeth-to-bob-on-our-chain-

`The sovereign account of H on D will be credited with 21 PolkaETH.`  => The sovereign account of H on D will be reduced with 21 PolkaETH

**Comment by vgeddes** [comment]
Thanks @carltraveler, good catch. I'll update the docs.
