### ISSUE TITLE
Consider using host function for keccak_512 in ethereum light client

### ISSUE THREAD

**Issue by musnit** [Snowfork/polkadot-ethereum#157]
We currently run our hashing via code in our parachain wasm binary. Ideally polkadot would add this as a host function we can use directly. If they do this, then we should port over to using it.

Comment on our PR: https://github.com/Snowfork/polkadot-ethereum/pull/147#discussion_r522148699
Comment on Substrate keccak: https://github.com/paritytech/substrate/commit/510e68b8d06a3d407eda0d4c1c330bd484140b65

**Comment by tomusdrw** [comment]
Substrate PR to track: https://github.com/paritytech/substrate/pull/7531

**Comment by Rizziepit** [comment]
This is sorted out. I switched to `sp_io::hashing::keccak_512` in 562de76
