### ISSUE TITLE
Update ethashproof merkle roots for Ethereum Lightclient

### ISSUE THREAD

**Issue by Rizziepit** [Snowfork/polkadot-ethereum#158]
Our ethash verification relies on having the merkle root of the DAG for the given epoch. We store these roots for the first 512 epochs here: https://github.com/Snowfork/polkadot-ethereum/blob/main/parachain/primitives/ethereum/src/ethashdata.rs. 512 epochs will run out after ~600 days from the date of this issue (very rough estimate based on current block production rate). We should update merkle roots well before that.

The merkle roots can be calculated using https://github.com/talbaneth/ethashproof

**Comment by Rizziepit** [comment]
**Deadline for this: Q1 of 2022**

**Comment by Rizziepit** [comment]
We should consider putting the DAG roots in chain state so that governance can update it.
Pros:
* We can update without modifying the runtime.
Cons:
* We are adding more chain storage reads in the `import_header` dispatchable which is already very expensive.
* We can just pre-compute more epochs

**Comment by musnit** [comment]
governance update to runtime vs governance update to DAG root field in chain state doesn't really seem that significantly different? especially if the latter is going to be more gas expensive on an ongoing basis, seems worse?

**Comment by philipstanislaus** [comment]
Yeah, that's a fair point @musnit . 

Can we recover from a situation where we did not update the roots? E. g. if verification fails, can we re-submit the same block after updating the root?

(Side note: I noticed recently that the substrate node/tx pool blacklists failed transactions, so if the hash is exactly the same, we might have an issue? Did not look further into this yet, could be that this is not an actual issue if the nonce changes.)

**Comment by Rizziepit** [comment]
> governance update to runtime vs governance update to DAG root field in chain state doesn't really seem that significantly different? especially if the latter is going to be more gas expensive on an ongoing basis, seems worse?

You're right about governance updates. But my intention is to entirely avoid an update, to runtime or roots, by hardcoding more roots now. My understanding is that, because this logic is for Eth 1.0 and PoW, our current runtime will inevitably require updates for Eth 2.0. The question is when? Is it worth bothering with a separate root updating mechanism if we can compute roots right now with a high degree of confidence?

>Can we recover from a situation where we did not update the roots? E. g. if verification fails, can we re-submit the same block after updating the root?

Yes, we can re-submit. The relayer / worker will automatically re-submit on restart with whatever the latest nonce is.

PS. Tx pool blacklisting shouldn't affect this because a PoW verification failure is not considered a failure at the tx pool level. Tx pool considers the tx successful if the nonce is valid and we process the tx, regardless of whether  the dispatchable returns `Ok` or `Error`. But even if some unexpected issue causes the tx to be blacklisted, the blacklisting expires after 30 minutes

**Comment by philipstanislaus** [comment]
You are right that we need to change the whole mechanism for ETH 2.0, so investing much into an improved roots updating mechanism seems not worth it. 

Great that re-submitting is already supported, so we can recover gracefully. 

Thanks for explaining blacklisting in more detail!

**Comment by musnit** [comment]
yep don't think we need to worry about a special mechanism for root updating at all. runtime upgrade is fine.

**Comment by Rizziepit** [comment]
Is an additional 2 years of runtime adequate?

**Comment by musnit** [comment]
yes
