### ISSUE TITLE
Ensure relayer syncs Substrate Eth Lightclient fast enough

### ISSUE THREAD

**Issue by Rizziepit** [Snowfork/polkadot-ethereum#170]
On fresh start / after downtime, the Substrate node's Ethereum header chain will be behind. We need to ensure that the relayer catches it up fast enough (see discussion [here](https://github.com/Snowfork/polkadot-ethereum/pull/166#discussion_r529822787)).

**Comment by vgeddes** [comment]
@Rizziepit would this relate to #240 (in that using Utility.batch could speed up sync)?

**Comment by musnit** [comment]
@Rizziepit this is not really even a significant issue anymore right? can be closed?

**Comment by Rizziepit** [comment]
We can recover from 1-day downtime in just over 1 hour, assuming decent hardware. I think that's good enough for MVP. I'll let you decide and close @musnit @vgeddes 

Btw, here's how I'm determining the recovery time:
* Eth blocks per day = ~6500
* Eth headers per Polkadot block = ~10 (depends heavily on hardware. This assumes a baseline of new-ish i7 CPU + SSD)
* Polkadot blocks per day = 14400 (assuming 6 second block time)

Time to recover from 1-day downtime = 1 / ( (10 x 14400 / 6500) - 1) = 0.0473 = 1.135 hours

**Comment by musnit** [comment]
yeh i think this is fine
