### ISSUE TITLE
Verify whether offchain storage for commitments could lead to data availability problems

### ISSUE THREAD

**Issue by philipstanislaus** [Snowfork/polkadot-ethereum#209]
See https://github.com/Snowfork/polkadot-ethereum/pull/205#pullrequestreview-568365393 for details

**Comment by Rizziepit** [comment]
To quote @vgeddes and the docs at https://substrate.dev/docs/en/knowledgebase/learn-substrate/off-chain-features#off-chain-indexing:

> ... off-chain indexing is populating the storage every time a block is processed, so the data is always consistent and will be exactly the same for every node with indexing enabled.

So, the only thing we need to ensure is that all nodes run with `--enable-offchain-indexing`. Then their offchain storage will be eventually consistent and contain the same messages.

@philipstanislaus feel free to re-open this if you still have unanswered questions.

**Comment by musnit** [comment]
@Rizziepit not sure this is true. i think as new transactions/blocks generate or update offchain state, new sections of the offchain state will eventually be consistent, but it's not clear if old sections or sections that are untouched will be shared and become consistent?

**Comment by philipstanislaus** [comment]
I think @Rizziepit is right, as long as nodes sync from scratch (or sync far enough back so the extrinsics with the oldest relevant messages are actually processed).

**Comment by Rizziepit** [comment]
@musnit the full quote from the docs is this:
```
Unlike OCWs, **which are not executed during initial blockchain synchronization**, off-chain indexing is populating the storage every time a block is processed, so the data is always consistent and will be exactly the same for every node with indexing enabled.
```

This implies to me that off-chain indexing happens during the initial sync, i.e. all state changes to off-chain storage are replayed. Like @philipstanislaus said, as long as we're doing a sync from the initial block or a safe block, we're golden.

I am assuming that, even if something like a "quick" or "warp" sync comes into existence (I am just throwing words around - I don't know the specifics of Polkadot), we will have the option to run our parachain node such that it does a "full" sync, i.e. the kind of sync described in the docs.
