### ISSUE TITLE
Flow control for long-range header catch up in relayer

### ISSUE THREAD

**Issue by Rizziepit** [Snowfork/polkadot-ethereum#233]
This issue pertains to the Eth -> Polkadot direction, but it might apply to the opposite direction too. When the relayer connects to a parachain node which is behind the current Ethereum tip, it will catch up the parachain node. It does this by sending headers one by one, in quick succession, until it reaches the tip. In the case that the node is 1000s of blocks behind the tip, the parachain node will likely be overwhelmed by incoming transactions. So we should implement flow control.

Also see https://github.com/Snowfork/polkadot-ethereum/pull/229 for context.

**Comment by Rizziepit** [comment]
https://github.com/Snowfork/polkadot-ethereum/pull/267 implements flow control and resolves this issue. However, long-range catchup is still very slow since we don't have bulk submission of headers. @musnit should we create a separate issue for that?

**Comment by musnit** [comment]
@Rizziepit I think slow long-range catchup is fine for now and the foreseeable future. I don't expect fast catchup to ever really be needed in production, as we're unlikely to have more than a few hours or at most a day downtime for the relayer, and even if something does go wrong that creates a longer delay, a slow catchup should still be sufficient to resolve it. Let's consider this resolved with #267 :)
