### ISSUE TITLE
Solidity applications should encode Substrate Call objects

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#239]
> 1. Is SCALE encoding on Ethereum necessary? In terms of gas optimization, it might more sense to just rely on abi encoding here, right?

@philipstanislaus yeah I'd say its necessary, as it has the potential to greatly simplify message dispatch to applications on the Substrate side. Right now the bridge module on Substrate has [hardwired links](https://github.com/Snowfork/polkadot-ethereum/blob/vincent/ethereum-receive-channel/parachain/pallets/bridge/src/lib.rs#L122) to the various application pallets, and that really hurts the bridge design in a number of ways.

The ultimate goal is to SCALE-encode a [Call](https://substrate.dev/rustdocs/v2.0.1/frame_support/dispatch/trait.Dispatchable.html) object which can be dispatched as-is on the Substrate side. This means Solidity contracts can issue messages which can result in calls to arbitrary dispatchables on any pallet (Obviously locked down though with verification of origins). @musnit and I discovered that `parity-bridges-common` devs were following the same approach for message dispatch (ref https://github.com/paritytech/parity-bridges-common/blob/master/modules/call-dispatch/src/lib.rs#L317)

Apparently, encoding a Call object is fairly straightforward, (after seeing how its done in GSRPC):
```javascript
call = ScaleCodec.Encode([PalletIndex, CallableIndex, Arg1, Arg2, ..., ArgN])
```

Then regarding gas costs, turns out that its not much expensive than ABI-encoding, since in many cases the Solidity `abi.encodePacked` generates data that has the same wire-format as SCALE. Specifically, this is true for the `bytes32`,  and `address` types. So in our current contracts we only need special handling for `uint256` which needs to be encoded in little-endian form:

```solidity
function encodePayload(OutboundPayload memory payload) private pure returns (bytes memory) {
    return abi.encodePacked(
        payload.sender,
        payload.recipient,
        payload.amount.toBytes32LE()
    );
}
```

Also `abi.encodePacked` isn't free either. It's a language primitive that gets compiled down to optimized assembly, which has  a gas cost regardless.

_Originally posted by @vgeddes in https://github.com/Snowfork/polkadot-ethereum/pull/237#issuecomment-771488489_

**Comment by musnit** [comment]
i think this is fine for now - we can optimize later on if needed and reconsider alternative encodings if the encoding becomes a significant piece contributing to gas usage.

this is also an application-level concern now, rather than bridge-wide, so not not really a big issue either way.
