### ISSUE TITLE
Naming convention: messages/commitment vs. commitment/commitment hash

### ISSUE THREAD

**Issue by denalimarsh** [Snowfork/polkadot-ethereum#273]
I mean it really depends on what we want "commitment" to mean, so I think we are just disputing semantics here.

In my mind, the parachain pledges that a set of messages are fit and proper to be relayed to Ethereum. Those messages are being committed to, ergo they are the commitment. The commitment happens to be uniquely identified by a hash of the messages being committed. In the same way that you can commit code with git and refer to that commit/commitment using a "commit hash" (which is a valid term in git).

I do think `commitment/commitmentHash` is preferable over `message/commitment` as it is more descriptive. It indicates that there is a relationship between the two things.

_Originally posted by @vgeddes in https://github.com/Snowfork/polkadot-ethereum/pull/266#discussion_r575133730_

**Comment by musnit** [comment]
closed because its not important
