### ISSUE TITLE
Substrate listener may be skipping some blocks

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#277]
Came across a situation like this at least twice today:

The parachain generated a commitment digest in the header for block 9. The relayer logged that it processed block 9 but did not detect a commitment digest. I verified that the parachain did indeed include the digest, so the relayer must be polling blocks incorrectly.

Looking over the substrate listener code, I do see that the `pollBlocks` function has very complicated logic for processing each block in order, mostly due to ensuring finality. We should double-check that it isnt perhaps skipping blocks.

**Comment by vgeddes** [comment]
Maybe instead of this intractable polling logic (which we inherited from the Chainbridge source code), we should probably use [SubscribeFinalizedHeads](https://pkg.go.dev/github.com/centrifuge/go-substrate-rpc-client@v1.1.0/rpc/chain#Chain.SubscribeFinalizedHeads) to just get headers as they are finalized.

Though I guess we will still need an alternate mode where we poll historical blocks using block numbers, so we can catch up after a relayer crash.

**Comment by musnit** [comment]
Hmm this is odd yeh - do you have any way to repro yet?

maybe it's querying pre-finalization or something?

SubscribeFinalizedHeads looks good though given we'll need the alternate mode based on querying blocks anyway, it may be best to just try get that working reliably first.

**Comment by musnit** [comment]
I encountered this too - still no clear way to repro but we'll need to have a way for the relayer to recover from that.

**Comment by musnit** [comment]
```
time="2021-03-04T16:58:14Z" level=info msg="Submitted header to Substrate" blockNumber=100 chain=Substrate
time="2021-03-04T16:58:15Z" level=debug msg="Processing block" block=15 chain=Substrate
time="2021-03-04T16:58:15Z" level=debug msg="Found commitment hash in header digest" block=16 chain=Substrate channelID="{false true}" commitmentHash=0xb5192bedc42c2c3f1a00b0a97704db85e12b4517ab388c1162ffa36bd7b3c604
time="2021-03-04T16:58:15Z" level=debug msg="Retrieved commitment from offchain storage" block=16 chain=Substrate commitmentSizeBytes=163
time="2021-03-04T16:58:15Z" level=debug msg="Processing block" block=16 chain=Substrate
time="2021-03-04T16:58:15Z" level=debug msg="Found commitment hash in header digest" block=16 chain=Substrate channelID="{false true}" commitmentHash=0xb5192bedc42c2c3f1a00b0a97704db85e12b4517ab388c1162ffa36bd7b3c604
time="2021-03-04T16:58:15Z" level=debug msg="Retrieved commitment from offchain storage" block=16 chain=Substrate commitmentSizeBytes=163
time="2021-03-04T16:58:15Z" level=debug msg="Processing block" block=17 chain=Substrate
time="2021-03-04T16:58:15Z" level=info msg="Transaction submitted" chain=Ethereum txHash=0x71f5d5e98ec4d77ed96bd9bc26daf92b2647e10fe311cbf3de158eb3fded7876
time="2021-03-04T16:58:15Z" level=error msg="Failed to submit transaction" chain=Ethereum error="the tx doesn't have the correct nonce. account has nonce of: 13 tx has nonce of: 12"
time="2021-03-04T16:58:15Z" level=error msg="Error submitting message to ethereum" chain=Ethereum error="the tx doesn't have the correct nonce. account has nonce of: 13 tx has nonce of: 12"
time="2021-03-04T16:58:18Z" level=debug msg="Witnessed new header" blockHash=0x18b7c29da3ff853065cb226ca94ac3fa91b22b9aee2528481e4409c5ea96cd60 blockNumber=101 chain=Ethereum
digest: 0x19ba33e22254dc4720711bafbe6fac1c4a97d0d22c3b6ae3f571dcf2e883ba43
ethash result: 0x113e3998692cdab56328c710cc61d38b3fc755f6a9723edfc381bdc4f2853486
time="2021-03-04T16:58:18Z" level=debug msg="Generated header from Ethereum header" blockHash=0x18b7c29da3ff853065cb226ca94ac3fa91b22b9aee2528481e4409c5ea96cd60 blockNumber=101 chain=Ethereum
```

just saw this

**Comment by vgeddes** [comment]
Just recording the conclusion from our discussion yesterday, the error `the tx doesn't have the correct nonce. account has nonce of: 13 tx has nonce of: 12` means we were probably were using the same account as the relayer for the demo. So not a relayer issue.

For the E2E tests we should probably make the relayer use account 9 provided by ganache:
```
(9) 0x87D987206180B8f3807Dd90455606eEa85cdB87a (100 ETH)
```

**Comment by musnit** [comment]
@vgeddes can we close this now with refactor/graceful restart functionality done?

**Comment by vgeddes** [comment]
Yes! I fixed this several weeks ago in https://github.com/Snowfork/polkadot-ethereum/pull/349. Resolved.
