### ISSUE TITLE
Use separate runtimes for our deployment stages

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#286]
Specifically because the verifier DescendantsUntilFinalized config setting needs to be different for local vs Ropsten vs Mainnet.

We need to set it to 3 for ropsten, 35 for ethereum, and 1 for E2E tests.

**Comment by Rizziepit** [comment]
Some context here: the hardcoding comes from parity-bridges-common's architecture, and I do think it's the best option. The runtime performance, and thus weights + security, is affected by this value (`DescendantsUntilFinalized` directly determines how many parent headers we need to read from storage). So our weight annotation for `import_header` will look something like:
```
#[weight = <T as Trait>::WeightInfo::import_header(DescendantsUntilFinalized)]
fn import_header(
```
The weight calculation should add 0 overhead. So loading a value from storage is not an option. We also have to make sure our benchmarks account for each value of `DescendantsUntilFinalized` that we might want to use. So it's appropriate to hard code a few supported values.

If we want to get rid of feature flags and needing to re-build for e2e tests, a better option is to construct multiple runtimes like parity-bridges-common

**Comment by Rizziepit** [comment]
There's probably some middle ground here between building multiple runtimes and completely dynamic values via chain spec. I'll leave that thinking to someone else :)

**Comment by vgeddes** [comment]
Ahh I understand better now. Yeah then given how the value affects weight, multiple runtimes will likely be the way to go.

I'll figure out how we can structure our code to support multiple runtimes.

**Comment by Rizziepit** [comment]
Heads up that https://github.com/Snowfork/polkadot-ethereum/pull/301/ introduces `DifficultyConfig` parameter which is also network-specific
