### ISSUE TITLE
Evaluate potential security risk of using tx.origin for user identification

### ISSUE THREAD

**Issue by alvatar** [Snowfork/polkadot-ethereum#299]
The use of tx.origin could be potentialy flawed from a security perspective. It's correnctly the design choice for user identification in messages incoming from Ethereum.
See [this](https://medium.com/coinmonks/solidity-tx-origin-attacks-58211ad95514) and [this](https://ethereum.stackexchange.com/questions/28972/who-is-msg-sender-when-calling-a-contract-from-a-contract/28974) as references.

**Comment by vgeddes** [comment]
@alvatar Hey, nope, we shouldn't use `tx.origin` at all. It's a big security/usability flaw.

My contracts-v2 branch updates the outbound channel contract, so that an origin address can be passed to submit: https://github.com/Snowfork/polkadot-ethereum/blob/vincent/channel-contracts-v2/ethereum/contracts/BasicOutboundChannel.sol#L21

If its necessary, the contract will need to verify that the supplied address is valid

**Comment by alvatar** [comment]
Great, that's a clean and secure solution, and the recommended one IIRC.
This will need to be changed in the relayer too @blablacio , and actulally it might not be necessary to change anything in the parachain code if that is encoded in the envelope as we did before with tx.origin.

**Comment by blablacio** [comment]
> @alvatar Hey, nope, we shouldn't use `tx.origin` at all. It's a big security/usability flaw as those references point out.
> 
> My contracts-v2 branch updates the outbound channel contract, so that an origin address can be passed to submit: https://github.com/Snowfork/polkadot-ethereum/blob/vincent/channel-contracts-v2/ethereum/contracts/BasicOutboundChannel.sol#L21
> 
> If its necessary, the contract will need to verify that the supplied address is valid. But perhaps that is not necessary for the basic channel.

Yep, I agree that's a better approach!

**Comment by blablacio** [comment]
> Great, that's a clean and secure solution, and the recommended one IIRC.
> This will need to be changed in the relayer too @blablacio , and actulally it might not be necessary to change anything in the parachain code if that is encoded in the envelope as we did before with tx.origin.

Don't think you'll need to change anything.

**Comment by vgeddes** [comment]
Just to add, in another iteration, we will need to add some kind of authorization mechanism, to ensure that the channels are actually allowed to use a supplied origin address.

So a user could call this first before allowing any app to send messages through the channel: `outboundChannel.authorize(appAddress)`

**Comment by vgeddes** [comment]
Since our ETHApp, ERC20App, and DOTApp are part of our trust-minimized system, we could add skip the authorizations when they are involved.

**Comment by vgeddes** [comment]
We've resolved to not use `tx.origin` anymore..
