### ISSUE TITLE
Add random tiebreaker to total difficulty tracking

### ISSUE THREAD

**Issue by Rizziepit** [Snowfork/polkadot-ethereum#300]
To calculate the total difficulty for the Eth chain, we sum the `header.difficulty` fields (see https://github.com/Snowfork/polkadot-ethereum/blob/ec687d9c6a1080ed2ab63c771b96660cdd65befa/parachain/pallets/verifier-lightclient/src/lib.rs#L275-L277). The problem with this is that `header.difficulty` represents the block's target difficulty, not its actual difficulty. We should be using the difficulty value returned by PoW verification.

**Comment by Rizziepit** [comment]
Turns out I misunderstood what `header.difficulty` represents, and our tracking is correct. The Geth implementation is here: https://github.com/ethereum/go-ethereum/blob/19d7a37abb9f3b9bf1a94baf6bd8c7d5042e54f8/core/blockchain.go#L1588-L1605

What we are missing is the random tiebreaker. I'm not sure if it's relevant to a bridge. @musnit want to weigh in on whether it's relevant? Description is here http://www.cs.cornell.edu/~ie53/publications/btcProcFC.pdf

**Comment by musnit** [comment]
Hmm at a glance I don't think tiebrieker matters, but will think about it further

**Comment by Rizziepit** [comment]
I did some reading. Afaict, the random tiebreaker is only relevant to miners. Miners implement this to increase the hash power threshold at which selfish mining becomes profitable. So not relevant to a bridge.
