### ISSUE TITLE
Ethereum listener should robustly relay messages

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#350]
The current listener has this behavior: For each new finalized block, relay the header, and followed by any messages.
 
However there is a bug where it will skip over the messages for the block if there was an error submitting those messages.

We should ensure the header and messages for a block are submitted atomically, and failing that, the relayer self-terminates or something like that.

Perhaps this will require some architectural changes in our channel logic.

**Comment by vgeddes** [comment]
@riz Maybe we could `Utility.batch` to submit the headers and messages atomically?

**Comment by musnit** [comment]
@vgeddes alternatively, we separate header relay and message relay completely into separate sub-services of the relayer that do not share any state, each with their own ethereum listener client, and allow them to each self-terminate and so get restarted independently. i think this may be a better pattern to follow across all our relay flows?

**Comment by Rizziepit** [comment]
@vgeddes yeah `Utility.batch` makes sense.

@musnit I'm not so sure about splitting it into sub-services. Well, not right now. If we want to make the relayer competitive in a multi-relayer world, sub-services probably make sense. But for the current one-relayer-only world, sub-services add complexity without much gain. We should chat some more

**Comment by musnit** [comment]
@Rizziepit yeh i would like us to get consensus on whether sub-services add or remove complexity. to me it seems like they'd maybe remove complexity? can discuss later on the call too

**Comment by vgeddes** [comment]
Thinking about it some more, and yeah I think independent sub-services is an attractive option. I think there could be issues with my suggestion of batching headers and messages in a single TX using `Utility.batch`. If the weight of the call is too high it might get rejected.

Also I suspect supporting multiple competing relayers may be a requirement for getting a common-good parachain slot.

If we go for independent sub services, the message listener would need a way to determine which block to relay. So we'll need to track the latest processed block number in the substrate inbound channels.

**Comment by musnit** [comment]
> If we go for independent sub services, the message listener would need a way to determine which block to relay. So we'll need to track the latest processed block number in the substrate inbound channels.
well we track the nonce, so can just infer the block number from that nonce by querying from ethereum like in https://github.com/Snowfork/polkadot-ethereum/pull/347

**Comment by vgeddes** [comment]
I prefer to track the block number. Its simpler as we don't need to scan historical blocks and all the events to find the nonce. Its nice to just be able to do a simple state query to find out which block to resume. Anyway we can discuss on the call.

**Comment by musnit** [comment]
> I prefer to track the block number. Its simpler as we don't need to scan historical blocks and all the events to find the nonce. Its nice to just be able to do a simple state query to find out which block to resume. Anyway we can discuss on the call.

sure - though will mean some extra on-chain cost and minor change to the protocol that could be avoided, but if its negligible then should be fine
