### ISSUE TITLE
Re-fetch metadata in every block

### ISSUE THREAD

**Issue by philipstanislaus** [Snowfork/polkadot-ethereum#381]
Just noticed that we do not currently re-fetch metadata on a regular basis. Metadata can change in theory at any time through a runtime upgrade. Not relevant here, will create a ticket for that.

_Originally posted by @philipstanislaus in https://github.com/Snowfork/polkadot-ethereum/pull/354#discussion_r617719418_

**Comment by musnit** [comment]
This may already be fine - assuming if the metadata changes, the relayer will get an error/crash and then restart and gracefully recover
