### ISSUE TITLE
Address review feedback for relayer & solidity

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#66]
Need to address review feedback from #58 and #59.

**Comment by denalimarsh** [comment]
Applies to open PR https://github.com/Snowfork/polkadot-ethereum/pull/57 as well

**Comment by denalimarsh** [comment]
https://github.com/Snowfork/polkadot-ethereum/pull/89 addresses the Solidity portions of this issue. @vgeddes are we good to close the issue?
