### ISSUE TITLE
Relayer should submit a mortal extrinsic

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#76]
From Philip:
> Immortal extrinsics are an issue indeed: Since nonces are tracked per account, and accounts can be reaped (nonce will be reset), any immortal transaction can be replayed.
> 
> Hence, anyone can mess up our bridge by replaying immortal extrinsics after a reap happens (even if accidentally).

**Comment by Rizziepit** [comment]
@vgeddes I was looking at the extrinsic construction code yesterday. What does mortal mean? What's the security implication here?

**Comment by musnit** [comment]
@Rizziepit https://wiki.polkadot.network/docs/en/build-protocol-info#transaction-mortality

**Comment by vgeddes** [comment]
I think we need to port this [function](https://substrate.dev/rustdocs/v2.0.1/src/sp_runtime/generic/era.rs.html#66) over to our relayer (or gsrpc) so we can initialize [ExtrinsicEra.AsMortalEra](https://github.com/Snowfork/go-substrate-rpc-client/blob/master/types/extrinsic_era.go#L26) correctly.

And then we also need to specify the starting block hash at https://github.com/Snowfork/polkadot-ethereum/blob/main/relayer/chain/substrate/writer.go#L135

**Comment by Rizziepit** [comment]
I merged https://github.com/Snowfork/polkadot-ethereum/pull/267 which constructs a mortal era with period 64. That translates roughly to an extrinsic being valid for ~6.4 minutes. We can play around with the value though
