### ISSUE TITLE
Add more descriptive alias for H160 in emitted Asset events

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#81]
See https://github.com/Snowfork/polkadot-ethereum/pull/79#discussion_r487689966

**Comment by philipstanislaus** [comment]
What about `BridgedAssetId`?

**Comment by vgeddes** [comment]
That name sounds good, I like it 😊

**Comment by musnit** [comment]
Yeh, though I wouldn't worry about this as the asset pallet will likely get replaced/augmented with general polkadot standardized asset pallets/interfaces.

**Comment by vgeddes** [comment]
Implemented in #93.
